apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: horror-game
  namespace: horror-game
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
spec:
  tls:
    - hosts:
        - horror-game.continuum.local
      secretName: horror-game-tls
  rules:
    - host: horror-game.continuum.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: horror-game
                port:
                  number: 80